#! /bin/sh

case "$1" in
    start)
        echo "Loading LDD Module"
        #load the scull driver on start-up
        /usr/bin/scull_load
        #load the faulty driver on start-up
        /usr/bin/module_load faulty
        #load hello module on start-up
        modprobe hello
        ;;
    stop)
        echo "Unloading LDD Module"
        #unload scull driver on shutdown
        /usr/bin/scull_unload
        #unload faulty driver on shutdown
        /usr/bin/module_unload faulty
        #unload hello module on shutdown
        rmmod hello
        ;;
    *)
        echo "Usage: $0 <start|stop>"
    	exit 1
esac

exit 0
