#! /bin/sh

case "$1" in
    start)
        echo "Loading LDD Module"
        #load the scull driver on start-up
        scull_load
        #load the faulty driver on start-up
        module_load faulty
        #load hello module on start-up
        modprobe hello
        #load aesd char driver module on start-up
        aesdchar_load
        ;;
    stop)
        echo "Unloading LDD Module"
        #unload scull driver on shutdown
        scull_unload
        #unload faulty driver on shutdown
        module_unload faulty
        #unload hello module on shutdown
        rmmod hello
        #unload aesd char driver module on shutdown
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 <start|stop>"
    	exit 1
esac

exit 0
